// <auto-generated />
namespace MySite.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class db51 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(db51));
        
        string IMigrationMetadata.Id
        {
            get { return "202002290727135_db51"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
